# IF YOU ARE HOSTING HELLBOT ON OTHER VPS OR LOCALLY RATHER THAN HEROKU
# THEN DON'T EDIT THIS FILE.
# GO AND EDIT ex_config.py AND RENAME IT TO config.py
# AND FILL THE REQUIRED VARS THERE.
# ONCE AGAIN!! 
# """DO NOT EDIT THIS FILE"""

import os
from telethon.tl.types import ChatBannedRights


class Config(object):
    LOGGER = True


# sorting configs soon....


class Production(Config):
    LOGGER = False


class Development(Config):
    LOGGER = True


# hellbot
