from .vars import Config


db_config = [
    "ALIVE_MSG",
    "ALIVE_NAME",
    "ALIVE_PIC",
    "ALIVE_TEMPLATE"
    "BAN_PIC",
    "BIO_MSG",
    "CUSTOM_PMPERMIT",
    "HELP_PIC",
    "PING_PIC",
    "PMPERMIT_PIC",
    "STICKER_PACKNAME",
    "USE_EVAL",
]

os_config = [
    "ABUSE",
    "API_HASH",
    "APP_ID",
    "BL_CHAT",
    "BOT_HANDLER",
    "BOT_LIBRARY",
    "BOT_TOKEN",
    "BOT_USERNAME",
    "BUTTONS_IN_HELP",
    "CURRENCY_API",
    "DATABASE_URL",
    "EMOJI_IN_HELP",
    "G_DRIVE_CLIENT_ID",
    "G_DRIVE_CLIENT_SECRET",
    "GDRIVE_FOLDER_ID",
    "GIT_REPO_NAME",
    "GITHUB_ACCESS_TOKEN",
    "HANDLER",
    "HEROKU_API_KEY",
    "HEROKU_APP_NAME",
    "INSTAGRAM_SESSION",
    "INSTANT_BLOCK",
    "LOGGER_ID",
    "LYRICS_API",
    "MAX_SPAM",
    "MY_CHANNEL",
    "MY_GROUP",
    "OCR_API",
    "PLUGIN_CHANNEL",
    "PM_LOGGER",
    "PM_PERMIT",
    "REMOVE_BG_API",
    "HELLBOT_SESSION",
    "SESSION_2",
    "SESSION_3",
    "SESSION_4",
    "SESSION_5",
    "SUDO_HANDLER",
    "SUDO_USERS",
    "TAG_LOGGER",
    "THUMB_IMG",
    "UNLOAD",
    "UPSTREAM_REPO",
    "UPSTREAM_REPO_BRANCH",
    "WEATHER_API",
]
